CC=gcc
CFLAGS=-I
Project1: Project1.c AllocateMemory.c WriteMemory.c DisplayMemory.c InvertMemory.c FreeMemory.c WritePattern.c 
	$(CC) -o Project1 Project1.c AllocateMemory.c WriteMemory.c DisplayMemory.c InvertMemory.c FreeMemory.c WritePattern.c  
clean: 
	rm -rf *.o Project1Sprint2
